### ISSUE TITLE
POST and error 403

### ISSUE THREAD

**Issue by shoabricot** [loopj/android-async-http#771]
Hi, I'm a beginner and try to implement a very simple REST client.
I tested my rest server with cURL (curl -X POST http://www.xxxxx.com/squeed/) and postman on simple request : GET / and POST /, that works.
I tried to implement android-async-http, GET request works but POST request give me a 403 error.

```java
client.post(context, BASE_URL, params,  "application/json", responseHandler);
//client.post(BASE_URL, params, responseHandler);
```

I tried different ways to do it : JSONHttpResponseHandler or AsyncHttpResponseHandler, different post method, params or no params, sniff packet with WireShark, ... always 403 error
Can't understand why GET request works and not POST.
Finally i tried this :

```java
new Thread(new Runnable() {
            //Thread to stop network calls on the UI thread
            public void run() {
                //Request the HTML
                // Create a new HttpClient and Post Header
                HttpClient httpclient = new DefaultHttpClient();
                HttpPost httppost = new HttpPost(BASE_URL);

                JSONObject jsonParams = new JSONObject();
                try {
                    jsonParams.put("latitude", 46.534187);
                    jsonParams.put("longitude", 6.562802);
                } catch (JSONException e) {
                    e.printStackTrace();
                }

                StringEntity se = null;
                try {
                    se = new StringEntity(jsonParams.toString());
                } catch (UnsupportedEncodingException e) {
                    e.printStackTrace();
                }

                httppost.setEntity(se);

                try {

                    // Execute HTTP Post Request
                    HttpResponse httpresponse = httpclient.execute(httppost);


                    String responseText = null;
                    try {
                        responseText = EntityUtils.toString(httpresponse.getEntity());
                        JSONObject json = new JSONObject(responseText);
                        Log.i("json", json.toString());
                    }catch (ParseException e) {
                        e.printStackTrace();
                        Log.i("Parse Exception", e + "");


                    } catch (JSONException e) {
                        e.printStackTrace();
                    }

                } catch (ClientProtocolException e) {
                    e.printStackTrace();
                    Log.i("Parse Exception", e + "");
                } catch (IOException e) {
                    e.printStackTrace();
                    Log.i("Parse Exception", e + "");
                }
            }
        }).start();
```

This works so maybe there is something I don't understand with the use of android-async-http.
Please can someone help me ?

**Comment by smarek** [comment]
403 means forbidden, either by server configuration or missing auth credentials. In code you said that works, i don't see any authentication set up, so it may be problem of URL. Have you checked that URL you're passing to AAH library is correct?

Also you could/should have some logging on server side, are there some logs, that could point out the issue/reason to return 403 ?

**Comment by shoabricot** [comment]
Hi Smarek, thanks for your answer.
I tried curl -X POST http://www.xxxxx.com/squeed/ and it responds correctly with my json datas, no 403 error. I also tried postman which is a great POST module for chrome to test requests. i sniffed the request sent with AAH and it's nearly the same than the postman request.

I use the same BASE_URL i use with GET request (GET requests work with AAH)
```java
client.post(context, BASE_URL, params,  "application/json", responseHandler);
```
I also tried different URL to be sure it was not a URL mistake.
I made my own REST server with https://github.com/jacwright/RestServer so i manage all request sent to my server.

postman request : works

POST /squeed/ HTTP/1.1
Host : www.xxxxxx.com
connection : keep-alive
content-length: 0
user-agent : chrome
cache-control : no-cache
accept : */*
accept-encoding : gzip, deflate
accept-language : fr-FR

AAH request : doesn't work

POST /squeed/ HTTP/1.1
Host : www.xxxxxx.com
connection : keep-alive
content-length: 0
cache-control : no-cache
accept : application/json
accept-encoding : gzip

i will try to add missing headers, maybe missing headers like user-agent are the reason of 403 error.

**Comment by shoabricot** [comment]
I fixed the problem : I must add "user-agent" in headers or I get a 403 error.

**Comment by TomIsYourName** [comment]
Hi @altab-ch , i got the same issue, and tried to add the header but still the same. Here is my code,

HttpPost httppost = new HttpPost(url);
httppost.addHeader("User-Agent", System.getProperty("http.agent"));
VibinLog.d(TAG, "User-Agent >>> " + System.getProperty("http.agent"));
httppost.addHeader("Content-Type", "application/x-www-form-urlencoded");

and the user-agent on my device is like this:

 Dalvik/2.1.0 (Linux; U; Android 5.1.1; Nexus 5 Build/LMY48B)

any suggestion? Thanks.

**Comment by smarek** [comment]
@TomIsYourName @altab-ch 

About User-Agent, you can set that through `AsyncHttpClient.setUserAgent(String)`
About `application/x-www-form-urlencoded` this is defined by `RequestParams` usage, see `RequestParams.setForceMultipartEntityContentType(Boolean)`, RequestParams will automatically use `multipart/form-data` or `application/x-www-form-urlencoded` based on what type of data you filled it with.

**Comment by TomIsYourName** [comment]
Thanks very much. I am using HttpPost on android client, already tried all
the way I have found, none of those is working. And I just read an article
about this, said it might be server error, will try to figure it out,
anyway, thanks for your help, will post the solution when I found it :D

**Comment by satyen893** [comment]
Hello there, I am using library version 1.4.6 in my project, everything was working fine till date, but today I am getting this forbidden response exception , when calling the URL using AndroidAsyncHttp.get method,.

I am sure about my request method that it is get and not post.

Same when tested in Postman REST client gives proper response without any exception , so any solution to this issue ??
