### ISSUE TITLE
Issue when uploading large number of data

### ISSUE THREAD

**Issue by vijaykd** [loopj/android-async-http#913]
I am trying to load large amount of data about 1600 of them to server. I get memory leak error. I have them running on For loop.

        12917-12917/com.ylg.all E/art﹕ Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
          07-29 21:56:51.852  12917-12917/com.ylg.all E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.ylg.all, PID: 12917
    java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
            at java.lang.Thread.nativeCreate(Native Method)
            at java.lang.Thread.start(Thread.java:1063)
            at org.apache.http.impl.conn.tsccm.AbstractConnPool.enableConnectionGC(AbstractConnPool.java:145)
            at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.createConnectionPool(ThreadSafeClientConnManager.java:125)
            at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.<init>(ThreadSafeClientConnManager.java:103)
            at com.loopj.android.http.AsyncHttpClient.<init>(AsyncHttpClient.java:238)
            at com.loopj.android.http.AsyncHttpClient.<init>(AsyncHttpClient.java:177)
            at com.loopj.android.http.AsyncHttpClient.<init>(AsyncHttpClient.java:147)
            at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2894)
            at android.app.ActivityThread.access$2100(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Not able find out the actual solution? What should be done when there is large amount of data to be uploaded?

**Comment by smarek** [comment]
About 1600 what? 1600 Bytes? 1600 KBytes ? 1600 MBytes ?
Also, that should not be problem, what is your code? Is it `POST` or `PUT` or `DELETE` method? How do you put the data into request?

**Comment by vijaykd** [comment]
1700 records (Each record contain 8 fields) so 1700 * 8 text.
Anyways, I am trying to post.

**Comment by vijaykd** [comment]
Code that I trying is here: http://justpaste.it/mo1q

**Comment by smarek** [comment]
Well, in your code `textDetailsBackUpDataOnline` uses `AsyncHttpClient.get` method, shouldn't that by `AsyncHttpClient.post` ?

**Comment by vijaykd** [comment]
I was actually trying post and get.. Sorry it is AsyncHttpClient.post and not AsyncHttpClient.get....

**Comment by smarek** [comment]
So the issue is fixed?

**Comment by vijaykd** [comment]
Nope. I still have the same issue. There is not error like above for smaller records.

**Comment by vijaykd** [comment]
Is there a way close the client for everything upload?

**Comment by vijaykd** [comment]
Is it the same for others who are using the api for large data?

**Comment by smarek** [comment]
So you did exchange the `.get` call with `.post` call and the same exception occurs?
What device do you run on and how large heap does the application use?
There is no need to close the client, both request and response are disposed of after request and callback completed
No, but your usecase is strange, sending 1700*8 text fields (spanning from 0 to ??? characters) shouldn't be done via `post` RequestParams, because that does make an form request (similar to when you have form on web-page and you submit it), better to put those data into `StringEntity` and post it or to put the data into file and upload the file.

**Comment by vijaykd** [comment]
Can you give me a logic on String Entity?

**Comment by vijaykd** [comment]
How come this is closed?
